### ISSUE TITLE
some question about sir_simulation.m

### ISSUE THREAD

**Issue by weike32** [gmuric/SIR_simulation#1]
This procedure has a very important reference value for me，But I am a little puzzled，At the first time step, why the parent_node is marked as a recovered node，Thank you if you can reply me。

**Comment by gmuric** [comment]
It was a bug. I fixed it. The source node was always recovered after first time step. Now, it is recovered with the probability rate r. You may notice an update on line 41 in the file "sir_simulation.m". Thanks for the comment. If you notice anything else, please let me know :)
